SELECT USER_ID, NICKNAME, SUM(PRICE)
FROM USED_GOODS_BOARD ugb
JOIN USED_GOODS_USER ugu
ON ugb.WRITER_ID = ugu.USER_ID
WHERE STATUS LIKE 'DONE'
GROUP BY USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY 3;