SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD ugb
JOIN USED_GOODS_USER ugu
ON ugb.WRITER_ID = ugu.USER_ID
WHERE STATUS LIKE 'DONE'
GROUP BY 1
HAVING TOTAL_SALES >= 700000
ORDER BY 3;